on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt install -y curl
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: curl https://ziglang.org/download/0.14.1/zig-x86_64-linux-0.14.1.tar.xz -o src/zig-x86_64-linux-0.14.1.tar.xz
      - run: curl https://ziglang.org/download/0.14.1/zig-x86_64-windows-0.14.1.zip -o src/zig-x86_64-windows-0.14.1.zip
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - run: zig build
      - run: zig build -Dtarget=x86_64-windows
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: zig-out/bin/buum
      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: zig-out/bin/buum.exe

  test_umka:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: curl -fL https://github.com/vtereshkov/umka-lang/releases/download/v1.5.5/umka_1.5.5_linux.zip -o umka_linux.zip
      - run: unzip umka_linux.zip
      - run: cd test/gen; UMKA=../../umka_*/umka ./run.sh

  test_fs:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/download-artifact@v4
        with:
          name: linux
          path: zig-out/bin
      - uses: actions/download-artifact@v4
        with:
          name: windows
          path: zig-out/bin

      - run: chmod +x zig-out/bin/buum

      - run: |
          cd test/fs
          sh run.sh
